### ISSUE TITLE
Error 'no timestamp' when using using url to load external javascripts

### ISSUE THREAD

**Issue by mmontenegro** [karma-runner/karma-requirejs#12]
When I configure require.js to use an external javascript like: 

// on require-config.js
paths: {
    'jquery': 'http://code.jquery.com/jquery-2.0.3'
}

I get: ERROR: 'There is no timestamp for http://code.jquery.com/jquery-2.0.3.js!

Should I do something different to make it work?

**Comment by jraller** [comment]
What would the impact be of changing the regex to also allow external links that don't specify protocol? One of my tests is loading a file that then loads an external resource from `//example.com/file.js` and I haven't been able to track down if it is Karma, karma-requirejs, or jasmine that is having trouble with it.

**Comment by Dignifiedquire** [comment]
Try changing the regex in your local karma installation and look if it works out. I think if you want to make a PR to also match `//` I'll consider. ( I don't think it will break anything, at least nothing that I know of)
