### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by mikkotikkanen** [karma-runner/karma-requirejs#32]
Nothing seems to have happened for the last year, even though the thing has some breaking issues. It has no documentation and even the ones that are there are pointing to 0.8, whereas latest Karma is 0.12. I think it fair to assume that it has been abandoned?

**Comment by aik099** [comment]
Are you referring to the Karma project or this sub-project for RequireJS compatibility?

I recommend contacting Karma Runner support via e-mail about that and post their response here.

**Comment by aik099** [comment]
I've just installed latest versions of all needed karma plugins and all my tests are running file. So I guess no changes are needed, where all stuff works anyway.

**Comment by Dignifiedquire** [comment]
No the project is not abandoned, but there are many karma plugins and not so many maintainers right now, so my time is stretched quite thin.
