### ISSUE TITLE
Automatically append ".js" when normalizing filename

### ISSUE THREAD

**Issue by kirill-konshin** [karma-runner/karma-requirejs#33]
```js
    normalized.push(parts[i]);
  }

  var file = normalized.pop();
  file += file.indexOf('.js') == -1 ? '.js' : '';
  normalized.push(file);

  return normalized.join('/');
```

Without that `karma-cajon`, the fork of this project, tries to load files without any extension. Since the author of the fork did not enabled issues -- I'll leave it here.

**Comment by kirill-konshin** [comment]
PR https://github.com/xdamman/karma-cajon/pull/1 created

**Comment by kirill-konshin** [comment]
Bump!

**Comment by lukeapage** [comment]
see https://github.com/karma-runner/karma/issues/513#issuecomment-48616784
